apiVersion: v1
kind: Service
metadata:  
      name: myflask
spec: 
   type: NodePort
   selector: 
       name: myflask
   ports: 
      - protocol: TCP
        port: 3200
        targetPort: 5001
        nodePort: 30010
